# Generated by Django 3.1.7 on 2021-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='floor_number',
        ),
    ]
