# Generated by Django 3.1.7 on 2021-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20210404_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='floor_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room_number',
            field=models.IntegerField(default=1),
        ),
    ]
