# Generated by Django 3.1.7 on 2021-04-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_remove_meeting_floor_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='room_number',
            new_name='room',
        ),
    ]
